language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r example_project/requirements.txt"
# command to run tests
script: python example_project/manage.py test fooapp
